Skip the derby benchmark on OpenJ9.
Gives the following crash:

```
Traceback (most recent call last):
  File "/home/kruninit/new_benchmarking_experiment/krun_ext_openj9.py", line 12, in <module>
    emit_process_exec_json(run("openj9", benchmark, int(num_iters)))
  File "/home/kruninit/new_benchmarking_experiment/krun_ext_common.py", line 197, in run
    res = post_process(done_exec, temp_file)
  File "/home/kruninit/new_benchmarking_experiment/krun_ext_common.py", line 228, in post_process
    return post_process_specjvm(done_exec)
  File "/home/kruninit/new_benchmarking_experiment/krun_ext_common.py", line 281, in post_process_specjvm
    raise ExecError(done_exec)
krun_ext_common.ExecError:
WARNING: process execution crashed

exit status:
0

args: ['/home/kruninit/new_benchmarking_experiment/OpenJDK11U-jdk_x64_linux_openj9_11.0.5_10_openj9-0.17.0/bin/java', '-Xms12G', '-Xmx12G', '-jar', '/home/kruninit/new_benchmarking_experiment/SPECjvm2008_1_01/SPECjvm2008.jar', '-Dspecjvm.home.dir=/home/kruninit/new_benchmarking_experiment/SPECjvm2008_1_01', '--lagom', '-ict', '-ikv', '--operations', '1', '-i', '2000', 'derby']

stdout:

SPECjvm2008 Lagom Workload
  Properties file:   none
  Base dir:          /home/kruninit/new_benchmarking_experiment/SPECjvm2008_1_01
  Benchmarks:        derby

  WARNING: Run will not be compliant.
  Property specjvm.run.checksum.validation must be true for publication.
  Not a compliant sequence of benchmarks for publication.
  Property specjvm.run.initial.check must be true for publication.

--- --- --- --- --- --- --- --- ---

  Benchmark:   derby
  Run mode:    static run
  Test type:   multi
  Threads:     4
  Iterations:  2000
  Run length:  1 operation
java.sql.SQLException: Failed to create database 'derby_dir/name1', see the next exception for details.
 at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
 at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
 at org.apache.derby.impl.jdbc.Util.seeNextException(Unknown Source)
 at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(Unknown Source)
 at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
 at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
 at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
 at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
 at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
 at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
 at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
 at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
 at spec.benchmarks.derby.DerbyHarness.getStartConnection(DerbyHarness.java:500)
 at spec.benchmarks.derby.DerbyHarness.createBaseDatabase(DerbyHarness.java:469)
 at spec.benchmarks.derby.DerbyHarness.createDatabases(DerbyHarness.java:431)
 at spec.benchmarks.derby.DerbyHarness.initDatabases(DerbyHarness.java:233)
 at spec.benchmarks.derby.Main.setupBenchmark(Main.java:99)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at spec.harness.ProgramRunner.invokeBmSetupBenchmark(ProgramRunner.java:183)
 at spec.harness.ProgramRunner.runBenchmark(ProgramRunner.java:301)
 at spec.harness.ProgramRunner.run(ProgramRunner.java:98)
Caused by: java.sql.SQLException: Failed to create database 'derby_dir/name1', see the next exception for details.
 at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
 at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
 ... 24 more
Caused by: java.sql.SQLException: Supplied territory description 'c.u_US' is invalid, expecting ln[_CO[_variant]]
ln=lower-case two-letter ISO-639 language code, CO=upper-case two-letter ISO-3166 country codes, see java.util.Locale.
 at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
 at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
 at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
 at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
 at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
 at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
 at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
 ... 21 more
Caused by: ERROR XBM0X: Supplied territory description 'c.u_US' is invalid, expecting ln[_CO[_variant]]
ln=lower-case two-letter ISO-639 language code, CO=upper-case two-letter ISO-3166 country codes, see java.util.Locale.
 at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
 at org.apache.derby.impl.services.monitor.BaseMonitor.staticGetLocaleFromString(Unknown Source)
 at org.apache.derby.impl.services.monitor.BaseMonitor.setLocale(Unknown Source)
 at org.apache.derby.impl.db.BasicDatabase.boot(Unknown Source)
 at org.apache.derby.impl.services.monitor.BaseMonitor.boot(Unknown Source)
 at org.apache.derby.impl.services.monitor.TopService.bootModule(Unknown Source)
 at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(Unknown Source)
 at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(Unknown Source)
 at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Unknown Source)
 ... 21 more

Iteration 1 (1 operation) begins: Sat Feb 15 02:50:32 GMT 2020
Iteration 1 (1 operation) ends:   Sat Feb 15 02:50:32 GMT 2020
Iteration 1 (1 operation) result:  **NOT VALID**

Errors in benchmark: derby
  [iter=1] Interrupted when joining benchmark thread 0: null
  [iter=1] java.lang.InterruptedException: null
java.base/java.lang.Object.wait(Native Method)
java.base/java.lang.Object.wait(Object.java:221)
java.base/java.lang.Thread.join(Thread.java:711)
spec.harness.ProgramRunner.runIteration(ProgramRunner.java:504)
spec.harness.ProgramRunner.runBenchmark(ProgramRunner.java:348)
spec.harness.ProgramRunner.run(ProgramRunner.java:98)

  [iter=1] Iteration failed.
  [iter=1][bt:1|op:1] Validation failure on line 1.
    Expected output:
    [001] sumB: 729526.57
    [002] sumD: 322387.26
    [003] sumT: 11894137.51
    [004] min call time: 1
    [005] max call time: 9999.9324
    [006] ...

    Received output:
    [001] java.sql.SQLException: Database 'derby_dir/name1' not found.
    [002]  at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
    [003]  at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
    [004]  at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
    [005]  at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
    [006] ...

Complete output: /home/kruninit/new_benchmarking_experiment/results/SPECjvm2008.021/derby.bt1.i1.op1.error.log
Validation file: /home/kruninit/new_benchmarking_experiment/SPECjvm2008_1_01/resources/derby/validity.derby.dat

  [iter=1][bt:3|op:1] Validation failure on line 1.
    Expected output:
    [001] sumB: 729526.57
    [002] sumD: 322387.26
    [003] sumT: 11894137.51
    [004] min call time: 1
    [005] max call time: 9999.9324
    [006] ...

    Received output:
    [001] java.sql.SQLException: Database 'derby_dir/name1' not found.
    [002]  at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
    [003]  at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
    [004]  at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
    [005]  at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
    [006] ...

Complete output: /home/kruninit/new_benchmarking_experiment/results/SPECjvm2008.021/derby.bt3.i1.op1.error.log
Validation file: /home/kruninit/new_benchmarking_experiment/SPECjvm2008_1_01/resources/derby/validity.derby.dat

  [iter=1][bt:4|op:1] Validation failure on line 1.
    Expected output:
    [001] sumB: 729526.57
    [002] sumD: 322387.26
    [003] sumT: 11894137.51
    [004] min call time: 1
    [005] max call time: 9999.9324
    [006] ...

    Received output:
    [001] java.sql.SQLException: Database 'derby_dir/name1' not found.
    [002]  at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
    [003]  at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
    [004]  at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
    [005]  at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
    [006] ...

Complete output: /home/kruninit/new_benchmarking_experiment/results/SPECjvm2008.021/derby.bt4.i1.op1.error.log
Validation file: /home/kruninit/new_benchmarking_experiment/SPECjvm2008_1_01/resources/derby/validity.derby.dat

  [iter=1][bt:2|op:1] Validation failure on line 1.
    Expected output:
    [001] sumB: 729526.57
    [002] sumD: 322387.26
    [003] sumT: 11894137.51
    [004] min call time: 1
    [005] max call time: 9999.9324
    [006] ...

    Received output:
    [001] java.sql.SQLException: Database 'derby_dir/name1' not found.
    [002]  at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
    [003]  at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
    [004]  at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
    [005]  at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
    [006] ...

Complete output: /home/kruninit/new_benchmarking_experiment/results/SPECjvm2008.021/derby.bt2.i1.op1.error.log
Validation file: /home/kruninit/new_benchmarking_experiment/SPECjvm2008_1_01/resources/derby/validity.derby.dat

Score on derby:  **NOT VALID**

Benchmark derby failed. Aborting run.

Results are stored in:
/home/kruninit/new_benchmarking_experiment/results/SPECjvm2008.021/SPECjvm2008.021.raw
Generating reports in:
/home/kruninit/new_benchmarking_experiment/results/SPECjvm2008.021
Error while creating report: java.lang.reflect.InvocationTargetException
java.lang.InternalError: java.lang.reflect.InvocationTargetException
 at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:86)
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:678)
 at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
 at java.desktop/sun.font.SunFontManager.getInstance(SunFontManager.java:247)
 at java.desktop/sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:265)
 at java.desktop/sun.java2d.SunGraphics2D.getFontMetrics(SunGraphics2D.java:856)
 at org.jfree.text.G2TextMeasurer.getStringWidth(G2TextMeasurer.java:79)
 at org.jfree.text.TextUtilities.nextLineBreak(TextUtilities.java:285)
 at org.jfree.text.TextUtilities.createTextBlock(TextUtilities.java:226)
 at org.jfree.text.TextUtilities.createTextBlock(TextUtilities.java:197)
 at org.jfree.chart.title.TextTitle.arrangeRR(TextTitle.java:489)
 at org.jfree.chart.title.TextTitle.arrange(TextTitle.java:450)
 at org.jfree.chart.JFreeChart.drawTitle(JFreeChart.java:1261)
 at org.jfree.chart.JFreeChart.draw(JFreeChart.java:1151)
 at org.jfree.chart.JFreeChart.createBufferedImage(JFreeChart.java:1349)
 at org.jfree.chart.JFreeChart.createBufferedImage(JFreeChart.java:1329)
 at org.jfree.chart.ChartUtilities.writeChartAsJPEG(ChartUtilities.java:414)
 at org.jfree.chart.ChartUtilities.saveChartAsJPEG(ChartUtilities.java:508)
 at org.jfree.chart.ChartUtilities.saveChartAsJPEG(ChartUtilities.java:460)
 at spec.reporter.Utils.createBmResultGraph(Utils.java:132)
 at spec.reporter.ReportGenerator.handleBenchmarkResult(ReportGenerator.java:160)
 at spec.reporter.ReportGenerator.handleBenchmarksResults(ReportGenerator.java:105)
 at spec.reporter.ReportGenerator.<init>(ReportGenerator.java:87)
 at spec.reporter.ReportGenerator.main2(ReportGenerator.java:750)
 at spec.reporter.Reporter.main2(Reporter.java:51)
 at spec.harness.Launch.createReport(Launch.java:307)
 at spec.harness.Launch.runBenchmarkSuite(Launch.java:250)
 at spec.harness.Launch.main(Launch.java:452)
Caused by: java.lang.reflect.InvocationTargetException
 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
 at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:84)
 ... 27 more
Caused by: java.lang.NullPointerException
 at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262)
 at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:225)
 at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:107)
 at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:719)
 at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:367)
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:678)
 at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:312)
 at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
 at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
 ... 32 more

stderr:
java.lang.NullPointerException
 at spec.benchmarks.derby.DerbyHarness.dropTable(DerbyHarness.java:291)
 at spec.benchmarks.derby.DerbyHarness.dropTables(DerbyHarness.java:304)
 at spec.benchmarks.derby.DerbyHarness.createBaseDatabase(DerbyHarness.java:470)
 at spec.benchmarks.derby.DerbyHarness.createDatabases(DerbyHarness.java:431)
 at spec.benchmarks.derby.DerbyHarness.initDatabases(DerbyHarness.java:233)
 at spec.benchmarks.derby.Main.setupBenchmark(Main.java:99)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at spec.harness.ProgramRunner.invokeBmSetupBenchmark(ProgramRunner.java:183)
 at spec.harness.ProgramRunner.runBenchmark(ProgramRunner.java:301)
 at spec.harness.ProgramRunner.run(ProgramRunner.java:98)
```